# Generated by Django 4.2.7 on 2023-11-11 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='The discount value, either a percentage or a fixed amount.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_usage', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this coupon has been used.')),
                ('active', models.BooleanField(help_text='Indicates whether the coupon is currently active or not.')),
            ],
        ),
    ]
